env:
  es6: true
  node: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  requireConfigFile: false
  babelOptions:
    babelrc: false
    configFile: false
    presets:
      - jest

plugins:
  - jest

extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:jest/recommended

rules:
  camelcase: off
  eslint-comments/no-use: off
  eslint-comments/no-unused-disable: off
  i18n-text/no-en: off
  import/no-commonjs: error    # Enforce ES modules only
  import/no-namespace: off
  no-console: off
  no-unused-vars: off
  prettier/prettier: error
  semi: off
